### ISSUE TITLE
About the runserver command

### ISSUE THREAD

**Issue by andrew-geeks** [FrisbTDW/bookstore#1]
Instead of writing 'python manage.py runserver 0.0.0.0:8000', just write '**python manage.py runserver**'.
then copy-paste the given address in cmd to the webrowser.
Because different computers have different addresses.

**Comment by FrisbTDW** [comment]
Mentioning the ip and the port (`ip:port`) lets you run the server at a specific ip. If you mention `0.0.0.0` as your ip and have already added your servers ip to `setting.py/ALLOWED_HOSTS`. You can access the website from any device connected to the same network and it makes debugging better.

**Comment by Frisb7** [comment]
Mentioning the ip and the port (`ip:port`) lets you run the server at a specific ip. If you mention `0.0.0.0` as your ip and have already added your servers ip to `Bookstore/setting.py/ALLOWED_HOSTS`. You can access the website from any device connected to the same network and it makes debugging better.
